### ISSUE TITLE
Stop updating repeating status history

### ISSUE THREAD

**Issue by otiskujawa** [Geoxor/Shaii#170]
```
/srv/bots/naoko-fix-various-bugs/node_modules/mongoose/lib/model.js:461
  return new VersionError(doc, version, modifiedPaths);
         ^
VersionError: No matching document found for id "redacted" version 124606 modifiedPaths "status_history"
    at generateVersionError (/srv/bots/naoko-fix-various-bugs/node_modules/mongoose/lib/model.js:461:10)
    at model.save (/srv/bots/naoko-fix-various-bugs/node_modules/mongoose/lib/model.js:518:28)
    at Function.schema.statics.pushHistory (file:///srv/bots/naoko-fix-various-bugs/src/naoko/Database.ts:164:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Logging.logPresenceUpdate (file:///srv/bots/naoko-fix-various-bugs/src/plugins/core/Logging.ts:191:7) {
  version: 124606,
  modifiedPaths: [ 'status_history' ]
}
```
some members are using status changing scripts and that leads to a lot of database traffic and crashes like this one
at this moment this is most frequent crash reason
it would be nice to just not update status history if it was already used
some of database records are at version 500 000+ because of that

**Comment by Its-treason** [comment]
And probably also create the functionality to delete entries older than X days or if there are more records than X already in the database.
